income = input("Enter your monthly income:")
expense = input("Enter your total monthly expenses:")
monthly_savings = int(income) - int(expense)
projected_savings = monthly_savings * 12 +( monthly_savings * 12 *0.05)
print("Enter your monthly income: ", income)
print("Enter your total monthly expenses: ", expense)
print("Your monthly savings are ", monthly_savings)
print("Projected savings after one year, with interest, is: ", projected_savings)